### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by brunohoske** [matheushoske/HoskesHoster-Issues#2]
![image](https://github.com/matheushoske/HoskesHoster-Issues/assets/124783417/ee22d236-29b8-42ea-adf0-a099b6e74719)

Detalhes:

Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.Exception: Ngrok dashboard did not start in 10 tries
   at MinecraftHoster.Services.NgrokService.GetPublicUrl() in E:\Projetos\HoskesHoster\HoskesHoster\Services\NgrokService.cs:line 75
   at MinecraftHoster.HosterHoskes.StartServer(String port) in E:\Projetos\HoskesHoster\HoskesHoster\HosterHoskes.cs:line 251
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

************** Assemblies Carregados **************
System.Private.CoreLib
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.CoreLib.dll
----------------------------------------
HoskesHoster
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///D:/Meus%20Arquivos/Downloads/HoskesHoster/HoskesHoster.dll
----------------------------------------
System.Runtime
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 6.0.2.0
    Versão do Win32: 6.0.1423.7402
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Versão do Assembly: 6.0.2.0
    Versão do Win32: 6.0.1423.7402
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Drawing.Common.dll
----------------------------------------
System.Net.Http
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Http.dll
----------------------------------------
System.Net.Http.Json
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Http.Json.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Net.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Private.Uri
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.Uri.dll
----------------------------------------
System.Memory
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Memory.dll
----------------------------------------
Microsoft.Win32.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.Concurrent
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Concurrent.dll
----------------------------------------
System.Net.Sockets
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.NonGeneric.dll
----------------------------------------
System.Security.Principal.Windows
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Text.Json
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Json.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Text.Encodings.Web
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Text.Encoding.Extensions
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Encoding.Extensions.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 6.0.1423.7402
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Resources.Extensions
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 6.0.2.0
    Versão do Win32: 6.0.1423.7402
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ObjectModel.dll
----------------------------------------
System.Linq
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.dll
----------------------------------------
Microsoft.Win32.Registry
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/Microsoft.Win32.Registry.dll
----------------------------------------
System.ComponentModel
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Diagnostics.Process
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.Process.dll
----------------------------------------
System.Linq.Parallel
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.Parallel.dll
----------------------------------------
System.Net.Requests
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Requests.dll
----------------------------------------
System.Net.WebHeaderCollection
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.ServicePoint
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.ServicePoint.dll
----------------------------------------
System.Linq.Expressions
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.Expressions.dll
----------------------------------------
Microsoft.CSharp
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/Microsoft.CSharp.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versão do Assembly: 0.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.CoreLib.dll
----------------------------------------
System.Console
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Console.dll
----------------------------------------
CliWrap
    Versão do Assembly: 3.6.0.0
    Versão do Win32: 3.6.0.0
    Base de Código: file:///D:/Meus%20Arquivos/Downloads/HoskesHoster/CliWrap.dll
----------------------------------------
System.IO.FileSystem
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.IO.FileSystem.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Runtime.Extensions
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Extensions.dll
----------------------------------------
System.Threading.Tasks
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.Tasks.dll
----------------------------------------
System.Threading.Timer
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.Timer.dll
----------------------------------------
System.Runtime.Loader
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 6.0.2.0
    Versão do Win32: 6.0.1423.7402
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/pt-BR/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Versão do Assembly: 6.0.0.0
    Versão do Win32: 6.0.1423.7309
    Base de Código: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Immutable.dll
----------------------------------------

************** Depuração JIT **************

**Comment by matheushoske** [comment]
Erro resolvido
